/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 public\\models\\trophy.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/trophy.glb')

  console.log(materials)
  
  const groupRef = useRef()
  
  useFrame((_, delta) => {
  groupRef.current.rotation.x += Math.PI/32 * delta
    groupRef.current.rotation.y += Math.PI/8 * delta
  })
  
  return (
    <group {...props} dispose={null} ref={groupRef}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials.gold} />
    </group>
  )
}

useGLTF.preload('/models/trophy.glb')
